### ISSUE TITLE
Error using combine_mriqc

### ISSUE THREAD

**Issue by martahedl** [garciadias/Neuroharmony#1]
Hi,
I tried getting familiar with neuroharmony and followed the instructions on the docs page (https://neuroharmony.readthedocs.io/en/latest/neuroharmony.html#combine-freesurfer-and-mriqc-data-on-the-neuroharmony-format-and-apply-the-result-on-a-trained-model). Everything went fine until the python-command

MRIQC = combine_mriqc(f'{mri_path}/derivatives/mriqc/') (error message see below)

I tried fixing the error myself (I also checked all my dependencies and found that I have the correct versions installed), but since I'm not super familiar with python, I have not been able to solve the issue, which is why I'm kindly asking for your help here. 

Thanks!
Marlene.

(PS: I don't think this has something to do with this, but there seems something missing in the instructions on the docs page, since the command 

participants_data = pd.read_csv(f'{mri_path}/participants.tsv', header=0, sep='\t', index_col=0)

won't work unless you specifiy "import pandas as pd". I added that line.)

Here is the error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/neuroharmony/data/combine_tools.py", line 70, in combine_mriqc
    pred = pd.read_csv(pred_path, header=0)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/common.py", line 200, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>
>>> import os
>>> MRIQC = combine_mriqc(f'{mri_path}/derivatives/mriqc/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/neuroharmony/data/combine_tools.py", line 70, in combine_mriqc
    pred = pd.read_csv(pred_path, header=0)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/pandas/io/common.py", line 200, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'list'>

**Comment by garciadias** [comment]
Hi @martahedl,

Thank you very much for your feedback. I have updated the documentation.

Let me know if have any more trouble, I would be happy to help.

Kind regards,

Rafael

**Comment by martahedl** [comment]
Hi Rafael, 

thanks for the quick response. Did you change something in the documentation besides adding the line "import pandas as pd" or did I miss something?

Unfortunately, I'm still getting the same error running the line "MRIQC = combine_mriqc(f'{mri_path}/derivatives/mriqc/')" (see output printed in the post above; it boils down to the error "ValueError: Invalid file path or buffer object type: <class 'list'>" I suppose).

Do you have any idea what could be wrong here?

Thanks again,
Marlene.

**Comment by garciadias** [comment]
Hi Marlene,

I just added the pandas import, sorry. Now I see you had the other problem. It seems that you are passing a list instead of a string in the variable mri_path.

You are supposed to use the path in your computer where you have your data in the BIDS format.
I will live the issue open if you have more questions. 

Thank you for your comment, 

Rafael

**Comment by martahedl** [comment]
Hi Rafael,

I did pass the path to the data in BIDS format to the mri_path using the following notation:

mri_path = '/Volumes/MarlenesPassport/neuroharmony_test/' 

(when checked that specific path for BIDS-validity using the bids validator command line)

The error persists... What am I missing?

Best,
Marlene.

**Comment by garciadias** [comment]
Hi Marlene,

I think I found the problem. You probably have more than one file starting with "mclf" in the folder "/Volumes/MarlenesPassport/neuroharmony_test/derivatives/mriqc/".
I will correct this in the code, but in the meanwhile, can you rename them to have only the one you want to use?

Cheers,

Rafael

**Comment by martahedl** [comment]
Hi Rafael,

yes, there were indeed 2 files in the mriqc/ folder starting iwth "mclf". What is the difference between those two? Since I was using the tutorial data I'm not quite sure about the experimental design here...

Re-naming one of the files (rather arbitrary) fixed my initial problem, such that the command

>>> MRIQC = combine_mriqc(f'{mri_path}/derivatives/mriqc/')

now runs without error.

However, now the next problem occurs with the next but one line of the tutorial instructions: 

neuroharmony = fetch_trained_model()

results in the error message

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/neuroharmony/data/collect_tools.py", line 82, in fetch_trained_model
    return joblib.load(filepath)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/Users/Marlene/miniconda3/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 342, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 187, in read
    array = self.read_array(unpickler)
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 138, in read_array
    read_size, "array data")
  File "/Users/Marlene/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle_utils.py", line 226, in _read_bytes
    raise ValueError(msg % (error_template, size, len(data)))
ValueError: EOF: reading array data, expected 42616 bytes got 37652

What might be the problem here?

Thanks again,
Marlene.

**Comment by garciadias** [comment]
Hi Marlene,

The idea here was to simplify the run of the mriqc, so the user don't have to learn that as well.
The problem is that every time you run mriqc it creates a output file with a different name. 
The "good" one should have the same number of lines as the group_T1w.tsv.
What I have done now is to use the first I found and raise a warning explaining the problem.
There maybe a legit reason for why you would have more than one. 
I will release the new version soon. You will have to pip install neuroharmony again.

This new error seems to be due to a corrupted file.
When you do neuroharmony.fetch_trained_model() it downloads the pretrained model and load it.
It has around 1.8GB. It maybe partially downloaded and than corrupted. Could you try to run it again?
If it fails again you can try:

```
pip uninstall neuroharmony
pip install neuroharmony
```
and try again.

Sorry for the trouble.

Cheers,

Rafael

**Comment by martahedl** [comment]
Hi Rafael,

unfortunately, re-running the fetch_trained_model() didn't do the trick, the same error persists. I also tried uninstalling and subsequently re-installing neuroharmony. Finally, I re-downloaded the tutorial data, but all these things didn't change the error message when running 

`neuroharmony = fetch_trained_model()`

Do you have any other ideas what's wrong?

**Comment by garciadias** [comment]
Hi Marlene,

By the error it seems the file is corrupted. Uninstalling should remove the file and redownload it again when you rerun the command.
Are you in python3.6?

You could try to directly download the pretrained model from: https://www.dropbox.com/s/s3521oqd3fpi0ll/neuroharmony.pkl.gz

To open it you do: 

```
neuroharmony = joblib.load(filepath)
```

Where filepath is the path to the neuroharmony.pkl.gz file.

Hope it helps.

Cheers
